// <auto-generated />
using System;
using EstudosEFCore.Models.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstudosEFCore.Migrations
{
    [DbContext(typeof(ControleFrotaContext))]
    partial class ControleFrotaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EstudosEFCore.Models.Domain.Entities.Motorista", b =>
                {
                    b.Property<string>("MotoristaId")
                        .HasColumnName("motor_id")
                        .HasColumnType("varchar(50)");

                    b.Property<sbyte?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ativo")
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1);

                    b.Property<string>("CNH")
                        .HasColumnName("cnh")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ValidadeCNH")
                        .HasColumnName("validadeCNH")
                        .HasColumnType("datetime");

                    b.HasKey("MotoristaId");

                    b.ToTable("tbl_motor");

                    b.HasData(
                        new
                        {
                            MotoristaId = "eb9c4fdc-992f-4e37-91e4-86d3e4e0a898",
                            Ativo = (sbyte)1,
                            CNH = "45698765498",
                            Nome = "Joao Marcos",
                            ValidadeCNH = new DateTime(2023, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MotoristaId = "5f4edb07-a52a-41cc-ba0a-40c8a884197d",
                            Ativo = (sbyte)1,
                            CNH = "6987589365",
                            Nome = "Francisco Fernando",
                            ValidadeCNH = new DateTime(2024, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EstudosEFCore.Models.Domain.Entities.MotoristaVeiculo", b =>
                {
                    b.Property<string>("VeiculoId")
                        .HasColumnName("veicl_id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotoristaId")
                        .HasColumnName("motor_id")
                        .HasColumnType("varchar(50)");

                    b.HasKey("VeiculoId", "MotoristaId");

                    b.HasIndex("MotoristaId");

                    b.ToTable("tbl_motr_veicl");

                    b.HasData(
                        new
                        {
                            VeiculoId = "e18505b9-525a-454f-a945-2f952ca166a1",
                            MotoristaId = "eb9c4fdc-992f-4e37-91e4-86d3e4e0a898"
                        },
                        new
                        {
                            VeiculoId = "bb473d85-7546-475e-a316-ed737ff029c4",
                            MotoristaId = "5f4edb07-a52a-41cc-ba0a-40c8a884197d"
                        });
                });

            modelBuilder.Entity("EstudosEFCore.Models.Domain.Entities.Veiculo", b =>
                {
                    b.Property<string>("VeiculoId")
                        .HasColumnName("veicl_id")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Ano")
                        .HasColumnName("ano")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnName("modelo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Placa")
                        .HasColumnName("placa")
                        .HasColumnType("varchar(20)");

                    b.HasKey("VeiculoId");

                    b.ToTable("tbl_veicl");

                    b.HasData(
                        new
                        {
                            VeiculoId = "e18505b9-525a-454f-a945-2f952ca166a1",
                            Ano = 2019,
                            Modelo = "Volvo FH 5540",
                            Placa = "HDT3B58"
                        },
                        new
                        {
                            VeiculoId = "bb473d85-7546-475e-a316-ed737ff029c4",
                            Ano = 2018,
                            Modelo = "Scania R450",
                            Placa = "DRG7T34"
                        });
                });

            modelBuilder.Entity("EstudosEFCore.Models.Domain.Entities.MotoristaVeiculo", b =>
                {
                    b.HasOne("EstudosEFCore.Models.Domain.Entities.Motorista", "Motorista")
                        .WithMany("Veiculos")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstudosEFCore.Models.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Motoristas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
